# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'M25_Widget2_logger.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(689, 764)
        Form.setMaximumSize(QtCore.QSize(16777215, 16777203))
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.VertLabel = QtWidgets.QLabel(Form)
        self.VertLabel.setObjectName("VertLabel")
        self.verticalLayout_3.addWidget(self.VertLabel)
        self.VertLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VertLineEdit.sizePolicy().hasHeightForWidth())
        self.VertLineEdit.setSizePolicy(sizePolicy)
        self.VertLineEdit.setObjectName("VertLineEdit")
        self.verticalLayout_3.addWidget(self.VertLineEdit)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.HorzLabel = QtWidgets.QLabel(Form)
        self.HorzLabel.setObjectName("HorzLabel")
        self.verticalLayout_2.addWidget(self.HorzLabel)
        self.HorzLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HorzLineEdit.sizePolicy().hasHeightForWidth())
        self.HorzLineEdit.setSizePolicy(sizePolicy)
        self.HorzLineEdit.setObjectName("HorzLineEdit")
        self.verticalLayout_2.addWidget(self.HorzLineEdit)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.EXPLabel = QtWidgets.QLabel(Form)
        self.EXPLabel.setObjectName("EXPLabel")
        self.verticalLayout_11.addWidget(self.EXPLabel)
        self.EXPLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EXPLineEdit.sizePolicy().hasHeightForWidth())
        self.EXPLineEdit.setSizePolicy(sizePolicy)
        self.EXPLineEdit.setObjectName("EXPLineEdit")
        self.verticalLayout_11.addWidget(self.EXPLineEdit)
        self.exposure_max_settings = QtWidgets.QLabel(Form)
        self.exposure_max_settings.setObjectName("exposure_max_settings")
        self.verticalLayout_11.addWidget(self.exposure_max_settings)
        self.gridLayout.addLayout(self.verticalLayout_11, 3, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.WritePLlabel = QtWidgets.QLabel(Form)
        self.WritePLlabel.setObjectName("WritePLlabel")
        self.verticalLayout_4.addWidget(self.WritePLlabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.WritePLineEdit = QtWidgets.QLineEdit(Form)
        self.WritePLineEdit.setObjectName("WritePLineEdit")
        self.horizontalLayout_2.addWidget(self.WritePLineEdit)
        self.BrowsePushButton = QtWidgets.QPushButton(Form)
        self.BrowsePushButton.setObjectName("BrowsePushButton")
        self.horizontalLayout_2.addWidget(self.BrowsePushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 2, 1, 2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ProjectNameLabel = QtWidgets.QLabel(Form)
        self.ProjectNameLabel.setObjectName("ProjectNameLabel")
        self.verticalLayout_5.addWidget(self.ProjectNameLabel)
        self.PNameLineEdit = QtWidgets.QLineEdit(Form)
        self.PNameLineEdit.setObjectName("PNameLineEdit")
        self.verticalLayout_5.addWidget(self.PNameLineEdit)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.GainLabel = QtWidgets.QLabel(Form)
        self.GainLabel.setObjectName("GainLabel")
        self.verticalLayout_7.addWidget(self.GainLabel)
        self.GainlineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GainlineEdit.sizePolicy().hasHeightForWidth())
        self.GainlineEdit.setSizePolicy(sizePolicy)
        self.GainlineEdit.setObjectName("GainlineEdit")
        self.verticalLayout_7.addWidget(self.GainlineEdit)
        self.gridLayout.addLayout(self.verticalLayout_7, 4, 1, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.BPPLabel = QtWidgets.QLabel(Form)
        self.BPPLabel.setObjectName("BPPLabel")
        self.verticalLayout_10.addWidget(self.BPPLabel)
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_10.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_10.addWidget(self.radioButton_2)
        self.gridLayout.addLayout(self.verticalLayout_10, 4, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.FPSLabel = QtWidgets.QLabel(Form)
        self.FPSLabel.setObjectName("FPSLabel")
        self.verticalLayout_9.addWidget(self.FPSLabel)
        self.FPSLineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FPSLineEdit.sizePolicy().hasHeightForWidth())
        self.FPSLineEdit.setSizePolicy(sizePolicy)
        self.FPSLineEdit.setObjectName("FPSLineEdit")
        self.verticalLayout_9.addWidget(self.FPSLineEdit)
        self.FPS_Max_settings = QtWidgets.QLabel(Form)
        self.FPS_Max_settings.setObjectName("FPS_Max_settings")
        self.verticalLayout_9.addWidget(self.FPS_Max_settings)
        self.gridLayout.addLayout(self.verticalLayout_9, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.CaptureModeLabel = QtWidgets.QLabel(Form)
        self.CaptureModeLabel.setObjectName("CaptureModeLabel")
        self.verticalLayout_8.addWidget(self.CaptureModeLabel)
        self.ZStackBox = QtWidgets.QCheckBox(Form)
        self.ZStackBox.setObjectName("ZStackBox")
        self.verticalLayout_8.addWidget(self.ZStackBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.StackFramesLabel = QtWidgets.QLabel(Form)
        self.StackFramesLabel.setObjectName("StackFramesLabel")
        self.verticalLayout_6.addWidget(self.StackFramesLabel)
        self.StackFramesEdit = QtWidgets.QLineEdit(Form)
        self.StackFramesEdit.setObjectName("StackFramesEdit")
        self.verticalLayout_6.addWidget(self.StackFramesEdit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 3, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.CaptureLabel = QtWidgets.QLabel(Form)
        self.CaptureLabel.setObjectName("CaptureLabel")
        self.verticalLayout_12.addWidget(self.CaptureLabel)
        self.CapTimeLineEdit = QtWidgets.QLineEdit(Form)
        self.CapTimeLineEdit.setObjectName("CapTimeLineEdit")
        self.verticalLayout_12.addWidget(self.CapTimeLineEdit)
        self.gridLayout.addLayout(self.verticalLayout_12, 3, 3, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.cycles_label = QtWidgets.QLabel(Form)
        self.cycles_label.setObjectName("cycles_label")
        self.verticalLayout_16.addWidget(self.cycles_label)
        self.cycles_linedit = QtWidgets.QLineEdit(Form)
        self.cycles_linedit.setObjectName("cycles_linedit")
        self.verticalLayout_16.addWidget(self.cycles_linedit)
        self.gridLayout.addLayout(self.verticalLayout_16, 6, 3, 1, 1)
        self.timelapse_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.timelapse_label.setFont(font)
        self.timelapse_label.setObjectName("timelapse_label")
        self.gridLayout.addWidget(self.timelapse_label, 5, 0, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.interval_label = QtWidgets.QLabel(Form)
        self.interval_label.setObjectName("interval_label")
        self.verticalLayout_15.addWidget(self.interval_label)
        self.interval_linedit = QtWidgets.QLineEdit(Form)
        self.interval_linedit.setObjectName("interval_linedit")
        self.verticalLayout_15.addWidget(self.interval_linedit)
        self.gridLayout.addLayout(self.verticalLayout_15, 6, 1, 1, 1)
        self.timelapse_check = QtWidgets.QCheckBox(Form)
        self.timelapse_check.setObjectName("timelapse_check")
        self.gridLayout.addWidget(self.timelapse_check, 6, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ConfButton = QtWidgets.QPushButton(Form)
        self.ConfButton.setObjectName("ConfButton")
        self.horizontalLayout.addWidget(self.ConfButton)
        self.AcquireCamsButton = QtWidgets.QPushButton(Form)
        self.AcquireCamsButton.setObjectName("AcquireCamsButton")
        self.horizontalLayout.addWidget(self.AcquireCamsButton)
        self.ReleaseCamsButton = QtWidgets.QPushButton(Form)
        self.ReleaseCamsButton.setObjectName("ReleaseCamsButton")
        self.horizontalLayout.addWidget(self.ReleaseCamsButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 3, 1, 1)
        self.summary_label = QtWidgets.QLabel(Form)
        self.summary_label.setObjectName("summary_label")
        self.gridLayout_2.addWidget(self.summary_label, 3, 3, 1, 1)
        self.loadBtn = QtWidgets.QPushButton(Form)
        self.loadBtn.setStyleSheet("background-color: rgb(255, 220, 42);")
        self.loadBtn.setObjectName("loadBtn")
        self.gridLayout_2.addWidget(self.loadBtn, 8, 3, 1, 1)
        self.ResolutionLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ResolutionLabel.setFont(font)
        self.ResolutionLabel.setObjectName("ResolutionLabel")
        self.gridLayout_2.addWidget(self.ResolutionLabel, 1, 3, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.exitBtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitBtn.sizePolicy().hasHeightForWidth())
        self.exitBtn.setSizePolicy(sizePolicy)
        self.exitBtn.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.exitBtn.setFont(font)
        self.exitBtn.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.exitBtn.setIconSize(QtCore.QSize(5, 5))
        self.exitBtn.setObjectName("exitBtn")
        self.gridLayout_3.addWidget(self.exitBtn, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CapturePushButton = QtWidgets.QPushButton(Form)
        self.CapturePushButton.setMinimumSize(QtCore.QSize(0, 17))
        self.CapturePushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CapturePushButton.setBaseSize(QtCore.QSize(0, 0))
        self.CapturePushButton.setStyleSheet("\n"
"background-color: rgb(0, 170, 0);")
        self.CapturePushButton.setObjectName("CapturePushButton")
        self.horizontalLayout_3.addWidget(self.CapturePushButton)
        self.LiveButton = QtWidgets.QPushButton(Form)
        self.LiveButton.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.LiveButton.setObjectName("LiveButton")
        self.horizontalLayout_3.addWidget(self.LiveButton)
        self.SingleCamCheckBox = QtWidgets.QCheckBox(Form)
        self.SingleCamCheckBox.setCheckable(True)
        self.SingleCamCheckBox.setChecked(False)
        self.SingleCamCheckBox.setObjectName("SingleCamCheckBox")
        self.horizontalLayout_3.addWidget(self.SingleCamCheckBox, 0, QtCore.Qt.AlignRight)
        self.CamSpinBox = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CamSpinBox.sizePolicy().hasHeightForWidth())
        self.CamSpinBox.setSizePolicy(sizePolicy)
        self.CamSpinBox.setMinimumSize(QtCore.QSize(165, 15))
        self.CamSpinBox.setObjectName("CamSpinBox")
        self.horizontalLayout_3.addWidget(self.CamSpinBox, 0, QtCore.Qt.AlignRight)
        self.CamSelectLabel = QtWidgets.QLabel(Form)
        self.CamSelectLabel.setObjectName("CamSelectLabel")
        self.horizontalLayout_3.addWidget(self.CamSelectLabel)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 7, 3, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toggleLED = QtWidgets.QPushButton(Form)
        self.toggleLED.setObjectName("toggleLED")
        self.horizontalLayout_5.addWidget(self.toggleLED)
        self.toggleDM = QtWidgets.QPushButton(Form)
        self.toggleDM.setObjectName("toggleDM")
        self.horizontalLayout_5.addWidget(self.toggleDM)
        self.testBtn = QtWidgets.QPushButton(Form)
        self.testBtn.setObjectName("testBtn")
        self.horizontalLayout_5.addWidget(self.testBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 10, 3, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.MsgLabel = QtWidgets.QLabel(Form)
        self.MsgLabel.setObjectName("MsgLabel")
        self.verticalLayout_13.addWidget(self.MsgLabel)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 667, 108))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logTextBox = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_3)
        self.logTextBox.setReadOnly(True)
        self.logTextBox.setObjectName("logTextBox")
        self.verticalLayout.addWidget(self.logTextBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_13.addWidget(self.scrollArea)
        self.gridLayout_2.addLayout(self.verticalLayout_13, 13, 3, 1, 1)
        self.summary_texEdit = QtWidgets.QTextEdit(Form)
        self.summary_texEdit.setReadOnly(True)
        self.summary_texEdit.setObjectName("summary_texEdit")
        self.gridLayout_2.addWidget(self.summary_texEdit, 4, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.VertLabel.setText(_translate("Form", "Vertical"))
        self.HorzLabel.setText(_translate("Form", "Horizontal"))
        self.EXPLabel.setText(_translate("Form", "Exposure(µs)"))
        self.exposure_max_settings.setText(_translate("Form", "MAX: "))
        self.WritePLlabel.setText(_translate("Form", "Image Write Path"))
        self.BrowsePushButton.setText(_translate("Form", "Browse"))
        self.ProjectNameLabel.setText(_translate("Form", "Project Name"))
        self.label.setText(_translate("Form", "Acquisition Settings"))
        self.GainLabel.setText(_translate("Form", "Gain(dB)"))
        self.BPPLabel.setText(_translate("Form", "Bits Per Pixel"))
        self.radioButton.setText(_translate("Form", "8 bpp"))
        self.radioButton_2.setText(_translate("Form", "12 bpp"))
        self.FPSLabel.setText(_translate("Form", "Frames Per Second"))
        self.FPS_Max_settings.setText(_translate("Form", "MAX:"))
        self.CaptureModeLabel.setText(_translate("Form", "Capture Mode"))
        self.ZStackBox.setText(_translate("Form", "Z-Stack"))
        self.StackFramesLabel.setText(_translate("Form", "Stack Frames Count:"))
        self.CaptureLabel.setText(_translate("Form", "Capture Time(s)"))
        self.cycles_label.setText(_translate("Form", "Cycles"))
        self.timelapse_label.setText(_translate("Form", "Timelapse Settings"))
        self.interval_label.setText(_translate("Form", "Interval [min]"))
        self.interval_linedit.setText(_translate("Form", "10"))
        self.timelapse_check.setText(_translate("Form", "Timelapse"))
        self.ConfButton.setText(_translate("Form", "SetConf"))
        self.AcquireCamsButton.setText(_translate("Form", "AcqCams"))
        self.ReleaseCamsButton.setText(_translate("Form", "FreeCams"))
        self.summary_label.setText(_translate("Form", "Summary:"))
        self.loadBtn.setText(_translate("Form", "Load Dataset"))
        self.ResolutionLabel.setText(_translate("Form", "Resolution"))
        self.exitBtn.setText(_translate("Form", "X"))
        self.CapturePushButton.setText(_translate("Form", "Capture"))
        self.LiveButton.setText(_translate("Form", "Live"))
        self.SingleCamCheckBox.setText(_translate("Form", "Single Cam"))
        self.CamSelectLabel.setText(_translate("Form", "Cam Select"))
        self.toggleLED.setText(_translate("Form", "Toggle LED"))
        self.toggleDM.setText(_translate("Form", "Toggle Digital Modulation"))
        self.testBtn.setText(_translate("Form", "Test me"))
        self.MsgLabel.setText(_translate("Form", "Messages:"))
