# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'M25_Widget2_logger.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(688, 783)
        Form.setMaximumSize(QtCore.QSize(16777215, 16777203))
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setSpacing(3)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 500))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.acquisition_tab = QtWidgets.QWidget()
        self.acquisition_tab.setObjectName("acquisition_tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.acquisition_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 421, 686))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.ResolutionLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ResolutionLabel.setFont(font)
        self.ResolutionLabel.setObjectName("ResolutionLabel")
        self.verticalLayout_19.addWidget(self.ResolutionLabel)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.WritePLlabel_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.WritePLlabel_3.setObjectName("WritePLlabel_3")
        self.verticalLayout_21.addWidget(self.WritePLlabel_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.browser_textedit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browser_textedit.sizePolicy().hasHeightForWidth())
        self.browser_textedit.setSizePolicy(sizePolicy)
        self.browser_textedit.setMinimumSize(QtCore.QSize(100, 10))
        self.browser_textedit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.browser_textedit.setObjectName("browser_textedit")
        self.horizontalLayout_7.addWidget(self.browser_textedit)
        self.browse_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.browse_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout_7.addWidget(self.browse_button)
        self.verticalLayout_21.addLayout(self.horizontalLayout_7)
        self.verticalLayout_20.addLayout(self.verticalLayout_21)
        self.ProjectNameLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ProjectNameLabel_2.setObjectName("ProjectNameLabel_2")
        self.verticalLayout_20.addWidget(self.ProjectNameLabel_2)
        self.project_linedit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.project_linedit.setMinimumSize(QtCore.QSize(100, 10))
        self.project_linedit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.project_linedit.setObjectName("project_linedit")
        self.verticalLayout_20.addWidget(self.project_linedit)
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        self.verticalLayout_2.addLayout(self.verticalLayout_19)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.ConfButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ConfButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ConfButton.setObjectName("ConfButton")
        self.gridLayout.addWidget(self.ConfButton, 5, 0, 1, 1)
        self.AcquireCamsButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AcquireCamsButton.sizePolicy().hasHeightForWidth())
        self.AcquireCamsButton.setSizePolicy(sizePolicy)
        self.AcquireCamsButton.setMinimumSize(QtCore.QSize(15, 0))
        self.AcquireCamsButton.setMaximumSize(QtCore.QSize(60, 60))
        self.AcquireCamsButton.setObjectName("AcquireCamsButton")
        self.gridLayout.addWidget(self.AcquireCamsButton, 5, 1, 1, 1)
        self.ReleaseCamsButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReleaseCamsButton.sizePolicy().hasHeightForWidth())
        self.ReleaseCamsButton.setSizePolicy(sizePolicy)
        self.ReleaseCamsButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ReleaseCamsButton.setObjectName("ReleaseCamsButton")
        self.gridLayout.addWidget(self.ReleaseCamsButton, 5, 3, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.EXPLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.EXPLabel.setObjectName("EXPLabel")
        self.verticalLayout_11.addWidget(self.EXPLabel)
        self.EXPLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EXPLineEdit.sizePolicy().hasHeightForWidth())
        self.EXPLineEdit.setSizePolicy(sizePolicy)
        self.EXPLineEdit.setMaximumSize(QtCore.QSize(100, 100))
        self.EXPLineEdit.setObjectName("EXPLineEdit")
        self.verticalLayout_11.addWidget(self.EXPLineEdit)
        self.exposure_max_settings = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.exposure_max_settings.setObjectName("exposure_max_settings")
        self.verticalLayout_11.addWidget(self.exposure_max_settings)
        self.gridLayout.addLayout(self.verticalLayout_11, 1, 1, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.GainLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.GainLabel.setObjectName("GainLabel")
        self.verticalLayout_7.addWidget(self.GainLabel)
        self.GainlineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GainlineEdit.sizePolicy().hasHeightForWidth())
        self.GainlineEdit.setSizePolicy(sizePolicy)
        self.GainlineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.GainlineEdit.setMaximumSize(QtCore.QSize(50, 50))
        self.GainlineEdit.setObjectName("GainlineEdit")
        self.verticalLayout_7.addWidget(self.GainlineEdit)
        self.gridLayout.addLayout(self.verticalLayout_7, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.FPSLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.FPSLabel.setObjectName("FPSLabel")
        self.verticalLayout_9.addWidget(self.FPSLabel)
        self.FPSLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FPSLineEdit.sizePolicy().hasHeightForWidth())
        self.FPSLineEdit.setSizePolicy(sizePolicy)
        self.FPSLineEdit.setMaximumSize(QtCore.QSize(50, 50))
        self.FPSLineEdit.setObjectName("FPSLineEdit")
        self.verticalLayout_9.addWidget(self.FPSLineEdit)
        self.FPS_Max_settings = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.FPS_Max_settings.setObjectName("FPS_Max_settings")
        self.verticalLayout_9.addWidget(self.FPS_Max_settings)
        self.gridLayout.addLayout(self.verticalLayout_9, 1, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.CaptureLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.CaptureLabel.setObjectName("CaptureLabel")
        self.verticalLayout_12.addWidget(self.CaptureLabel)
        self.CapTimeLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.CapTimeLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.CapTimeLineEdit.setObjectName("CapTimeLineEdit")
        self.verticalLayout_12.addWidget(self.CapTimeLineEdit)
        self.memory_available = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.memory_available.setObjectName("memory_available")
        self.verticalLayout_12.addWidget(self.memory_available)
        self.gridLayout.addLayout(self.verticalLayout_12, 1, 3, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.CaptureModeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.CaptureModeLabel.setObjectName("CaptureModeLabel")
        self.verticalLayout_8.addWidget(self.CaptureModeLabel)
        self.ZStackBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.ZStackBox.setObjectName("ZStackBox")
        self.verticalLayout_8.addWidget(self.ZStackBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.StackFramesLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.StackFramesLabel.setObjectName("StackFramesLabel")
        self.verticalLayout_6.addWidget(self.StackFramesLabel)
        self.StackFramesEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StackFramesEdit.sizePolicy().hasHeightForWidth())
        self.StackFramesEdit.setSizePolicy(sizePolicy)
        self.StackFramesEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.StackFramesEdit.setObjectName("StackFramesEdit")
        self.verticalLayout_6.addWidget(self.StackFramesEdit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 3, 1, 1)
        self.timelapse_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.timelapse_label.setFont(font)
        self.timelapse_label.setObjectName("timelapse_label")
        self.gridLayout.addWidget(self.timelapse_label, 3, 0, 1, 1)
        self.timelapse_check = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.timelapse_check.setObjectName("timelapse_check")
        self.gridLayout.addWidget(self.timelapse_check, 4, 0, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.interval_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.interval_label.setObjectName("interval_label")
        self.verticalLayout_15.addWidget(self.interval_label)
        self.interval_linedit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interval_linedit.sizePolicy().hasHeightForWidth())
        self.interval_linedit.setSizePolicy(sizePolicy)
        self.interval_linedit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.interval_linedit.setObjectName("interval_linedit")
        self.verticalLayout_15.addWidget(self.interval_linedit)
        self.gridLayout.addLayout(self.verticalLayout_15, 4, 1, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.cycles_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cycles_label.setObjectName("cycles_label")
        self.verticalLayout_16.addWidget(self.cycles_label)
        self.cycles_linedit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cycles_linedit.sizePolicy().hasHeightForWidth())
        self.cycles_linedit.setSizePolicy(sizePolicy)
        self.cycles_linedit.setMaximumSize(QtCore.QSize(100, 100))
        self.cycles_linedit.setObjectName("cycles_linedit")
        self.verticalLayout_16.addWidget(self.cycles_linedit)
        self.gridLayout.addLayout(self.verticalLayout_16, 4, 3, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.BPPLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BPPLabel.sizePolicy().hasHeightForWidth())
        self.BPPLabel.setSizePolicy(sizePolicy)
        self.BPPLabel.setObjectName("BPPLabel")
        self.verticalLayout_10.addWidget(self.BPPLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_10, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.loadBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadBtn.sizePolicy().hasHeightForWidth())
        self.loadBtn.setSizePolicy(sizePolicy)
        self.loadBtn.setMaximumSize(QtCore.QSize(350, 16777215))
        self.loadBtn.setStyleSheet("background-color: rgb(255, 220, 42);")
        self.loadBtn.setObjectName("loadBtn")
        self.verticalLayout_2.addWidget(self.loadBtn)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CapturePushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.CapturePushButton.setMinimumSize(QtCore.QSize(0, 17))
        self.CapturePushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CapturePushButton.setBaseSize(QtCore.QSize(0, 0))
        self.CapturePushButton.setStyleSheet("\n"
"background-color: rgb(0, 170, 0);")
        self.CapturePushButton.setObjectName("CapturePushButton")
        self.horizontalLayout_3.addWidget(self.CapturePushButton)
        self.LiveButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.LiveButton.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.LiveButton.setObjectName("LiveButton")
        self.horizontalLayout_3.addWidget(self.LiveButton)
        self.SingleCamCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.SingleCamCheckBox.setCheckable(True)
        self.SingleCamCheckBox.setChecked(False)
        self.SingleCamCheckBox.setObjectName("SingleCamCheckBox")
        self.horizontalLayout_3.addWidget(self.SingleCamCheckBox, 0, QtCore.Qt.AlignRight)
        self.CamSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.CamSpinBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CamSpinBox.sizePolicy().hasHeightForWidth())
        self.CamSpinBox.setSizePolicy(sizePolicy)
        self.CamSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.CamSpinBox.setMaximumSize(QtCore.QSize(50, 50))
        self.CamSpinBox.setObjectName("CamSpinBox")
        self.horizontalLayout_3.addWidget(self.CamSpinBox)
        self.CamSelectLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.CamSelectLabel.setObjectName("CamSelectLabel")
        self.horizontalLayout_3.addWidget(self.CamSelectLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toggleLED = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.toggleLED.setObjectName("toggleLED")
        self.horizontalLayout_5.addWidget(self.toggleLED)
        self.toggleDM = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.toggleDM.setObjectName("toggleDM")
        self.horizontalLayout_5.addWidget(self.toggleDM)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.MsgLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.MsgLabel.setObjectName("MsgLabel")
        self.verticalLayout_13.addWidget(self.MsgLabel)
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 415, 230))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logTextBox = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logTextBox.sizePolicy().hasHeightForWidth())
        self.logTextBox.setSizePolicy(sizePolicy)
        self.logTextBox.setMinimumSize(QtCore.QSize(300, 200))
        self.logTextBox.setReadOnly(True)
        self.logTextBox.setObjectName("logTextBox")
        self.verticalLayout.addWidget(self.logTextBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_13.addWidget(self.scrollArea)
        self.verticalLayout_2.addLayout(self.verticalLayout_13)
        self.tabWidget.addTab(self.acquisition_tab, "")
        self.developer_tab = QtWidgets.QWidget()
        self.developer_tab.setObjectName("developer_tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.developer_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 278, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.VertLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VertLabel.setObjectName("VertLabel")
        self.verticalLayout_3.addWidget(self.VertLabel)
        self.VertLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VertLineEdit.sizePolicy().hasHeightForWidth())
        self.VertLineEdit.setSizePolicy(sizePolicy)
        self.VertLineEdit.setObjectName("VertLineEdit")
        self.verticalLayout_3.addWidget(self.VertLineEdit)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.HorzLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.HorzLabel.setObjectName("HorzLabel")
        self.verticalLayout_14.addWidget(self.HorzLabel)
        self.HorzLineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HorzLineEdit.sizePolicy().hasHeightForWidth())
        self.HorzLineEdit.setSizePolicy(sizePolicy)
        self.HorzLineEdit.setObjectName("HorzLineEdit")
        self.verticalLayout_14.addWidget(self.HorzLineEdit)
        self.gridLayout_4.addLayout(self.verticalLayout_14, 0, 1, 1, 1)
        self.tabWidget.addTab(self.developer_tab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 1, 1, 1)
        self.exitBtn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitBtn.sizePolicy().hasHeightForWidth())
        self.exitBtn.setSizePolicy(sizePolicy)
        self.exitBtn.setMinimumSize(QtCore.QSize(20, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.exitBtn.setFont(font)
        self.exitBtn.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.exitBtn.setIconSize(QtCore.QSize(5, 5))
        self.exitBtn.setObjectName("exitBtn")
        self.gridLayout_3.addWidget(self.exitBtn, 0, 0, 1, 1)
        self.verticalLayout_22.addLayout(self.gridLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout_22, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ResolutionLabel.setText(_translate("Form", "Save Information"))
        self.WritePLlabel_3.setText(_translate("Form", "Image Write Path"))
        self.browse_button.setText(_translate("Form", "Browse"))
        self.ProjectNameLabel_2.setText(_translate("Form", "Project Name"))
        self.ConfButton.setText(_translate("Form", "SetConf"))
        self.AcquireCamsButton.setText(_translate("Form", "AcqCams"))
        self.ReleaseCamsButton.setText(_translate("Form", "FreeCams"))
        self.EXPLabel.setText(_translate("Form", "Exposure(µs)"))
        self.exposure_max_settings.setText(_translate("Form", "MAX: "))
        self.GainLabel.setText(_translate("Form", "Gain(dB)"))
        self.label.setText(_translate("Form", "Acquisition Settings"))
        self.FPSLabel.setText(_translate("Form", "Frames Per Second"))
        self.FPS_Max_settings.setText(_translate("Form", "MAX:"))
        self.CaptureLabel.setText(_translate("Form", "Capture Time(s)"))
        self.memory_available.setText(_translate("Form", "Memory Available: "))
        self.CaptureModeLabel.setText(_translate("Form", "Capture Mode"))
        self.ZStackBox.setText(_translate("Form", "Z-Stack"))
        self.StackFramesLabel.setText(_translate("Form", "# Z-frames"))
        self.timelapse_label.setText(_translate("Form", "Timelapse Settings"))
        self.timelapse_check.setText(_translate("Form", "Timelapse"))
        self.interval_label.setText(_translate("Form", "Interval [min]"))
        self.interval_linedit.setText(_translate("Form", "10"))
        self.cycles_label.setText(_translate("Form", "Cycles"))
        self.BPPLabel.setText(_translate("Form", "Bits Per Pixel"))
        self.radioButton.setText(_translate("Form", "8 bpp"))
        self.radioButton_2.setText(_translate("Form", "12 bpp"))
        self.loadBtn.setText(_translate("Form", "Load Dataset"))
        self.CapturePushButton.setText(_translate("Form", "Capture"))
        self.LiveButton.setText(_translate("Form", "Live"))
        self.SingleCamCheckBox.setText(_translate("Form", "Single Cam"))
        self.CamSelectLabel.setText(_translate("Form", "Cam Select"))
        self.toggleLED.setText(_translate("Form", "Toggle LED"))
        self.toggleDM.setText(_translate("Form", "Toggle Digital Modulation"))
        self.MsgLabel.setText(_translate("Form", "Messages:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.acquisition_tab), _translate("Form", "Acquisition"))
        self.VertLabel.setText(_translate("Form", "Vertical"))
        self.HorzLabel.setText(_translate("Form", "Horizontal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.developer_tab), _translate("Form", "Developer Settings"))
        self.exitBtn.setText(_translate("Form", "X"))
